/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joaoa
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */ 
    Questao1 questao1 = new Questao1();
    Questao2 questao2 = new Questao2();
    Questao3 questao3 = new Questao3();
    Questao4 questao4 = new Questao4();
    Questao5 questao5 = new Questao5();
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaInterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_questao1 = new javax.swing.JMenuItem();
        menu_questao2 = new javax.swing.JMenuItem();
        menu_questao3 = new javax.swing.JMenuItem();
        menu_questao4 = new javax.swing.JMenuItem();
        menu_questao5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout TelaInternaLayout = new javax.swing.GroupLayout(TelaInterna);
        TelaInterna.setLayout(TelaInternaLayout);
        TelaInternaLayout.setHorizontalGroup(
            TelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        TelaInternaLayout.setVerticalGroup(
            TelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_go-home_118770.png"))); // NOI18N
        jMenu1.setText("Questões");

        menu_questao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Safe_box_65653.png"))); // NOI18N
        menu_questao1.setText("Questão 1");
        menu_questao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_questao1ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_questao1);

        menu_questao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_number_123_1_1553071.png"))); // NOI18N
        menu_questao2.setText("Questão 2");
        menu_questao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_questao2ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_questao2);

        menu_questao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Finance_loan_money_1889199.png"))); // NOI18N
        menu_questao3.setText("Questão 3");
        menu_questao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_questao3ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_questao3);

        menu_questao4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_number_123_1553072.png"))); // NOI18N
        menu_questao4.setText("Questão 4");
        menu_questao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_questao4ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_questao4);

        menu_questao5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Create_32451.png"))); // NOI18N
        menu_questao5.setText("Questão 5");
        menu_questao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_questao5ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_questao5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaInterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaInterna)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_questao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_questao1ActionPerformed
        MostrarTelas(true, false, false, false, false);
        questao1.setVisible(true);
    }//GEN-LAST:event_menu_questao1ActionPerformed

    private void menu_questao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_questao2ActionPerformed
        MostrarTelas(false, true, false, false, false);
        questao2.setVisible(true);
    }//GEN-LAST:event_menu_questao2ActionPerformed

    private void menu_questao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_questao3ActionPerformed
        MostrarTelas(false, false, true, false, false);
        questao3.setVisible(true);
    }//GEN-LAST:event_menu_questao3ActionPerformed

    private void menu_questao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_questao4ActionPerformed
        MostrarTelas(false, false, false, true, false);
        questao4.setVisible(true);
    }//GEN-LAST:event_menu_questao4ActionPerformed

    private void menu_questao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_questao5ActionPerformed
        MostrarTelas(false, false, false, false, true);
        questao5.setVisible(true);
    }//GEN-LAST:event_menu_questao5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane TelaInterna;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_questao1;
    private javax.swing.JMenuItem menu_questao2;
    private javax.swing.JMenuItem menu_questao3;
    private javax.swing.JMenuItem menu_questao4;
    private javax.swing.JMenuItem menu_questao5;
    // End of variables declaration//GEN-END:variables

    public void MostrarTelas(boolean a, boolean b, boolean c, boolean d, boolean e){
        TelaInterna.add(questao1);
        TelaInterna.add(questao2);
        TelaInterna.add(questao3);
        TelaInterna.add(questao4);
        TelaInterna.add(questao5);
    }
}
